@signUpUrl={{baseUrl}}/signup


POST {{signUpUrl}}
Content-Type: application/json

{
    "name": "Mateus",
    "email": "email@email.com",
    "password": "123",
    "passwordConfirmation": "123"
}